spring:
  application:
    name: ms-token
  profiles:
    active: ${ENVIRONMENT:local}
  cloud:
    config:
      fail-fast: false
      uri: ${SERVICE_CONFIG_URI:http://configserver:8080}
      basedir: ´${SERVICE_CONFIG_BASEDIR}´

server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT-PATH:/api/v1}