spring:
  application:
    name: ms-token
  profiles:
    active: ${ENVIRONMENT:local}
  cloud:
    config:
      fail-fast: false
      uri: ${SERVICE_CONFIG_URI:http://configserver:8080}
      basedir: ´${SERVICE_CONFIG_BASEDIR}´

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/token
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:prices;DB_CLOSE_DELAY=-1
    username: sa
    password:
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT-PATH:/api/v1}

tokens:
  expiration: 60

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics